### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by evanchooly** [evanchooly/javabot#156]
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.lang.String.substring(String.java:1963)
        at javabot.operations.URLTitleOperation.findTitle(URLTitleOperation.kt:68)
        at javabot.operations.URLTitleOperation.handleChannelMessage(URLTitleOperation.kt:25)
        at javabot.Javabot.getChannelResponses(Javabot.kt:341)
        at javabot.Javabot.processMessage(Javabot.kt:269)
        at javabot.IrcAdapter$onMessage$1.run(IrcAdapter.kt:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jottinger** [comment]
On what input?

**Comment by evanchooly** [comment]
doesn't say

**Comment by jottinger** [comment]
Problem found from the stack trace, surprise:

` if (loop && !url.substring(0, 10).contains("//www.")) {`

The fix is:

` if (loop && url.length > 10 && !url.substring(0, 10).contains("//www.")) {`

But I haven't been able to test this out to validate a failing URL; my DNS is returning a safe page for urls that should qualify to show the bug.

**Comment by evanchooly** [comment]
@jottinger fixed this
