### ISSUE TITLE
NPE in throttler

### ISSUE THREAD

**Issue by evanchooly** [evanchooly/javabot#81]
```java
java.lang.NullPointerException
        at java.time.Duration.between(Duration.java:473)
        at javabot.operations.throttle.Throttler.validateNickServAccount(Throttler.java:79)
        at javabot.operations.throttle.Throttler.isThrottled(Throttler.java:48)
        at javabot.Javabot.processMessage(Javabot.java:289)
        at javabot.BotListener.lambda$onMessage$14(BotListener.java:77)
        at javabot.BotListener$$Lambda$29/1950561585.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by evanchooly** [comment]
trace no longer matches code.  will reopen if it happens again.
