### ISSUE TITLE
URISyntaxException in URLTitleOperation

### ISSUE THREAD

**Issue by evanchooly** [evanchooly/javabot#82]
```java
java.lang.IllegalArgumentException: Expected authority at index 7: http://
        at java.net.URI.create(URI.java:852)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
        at javabot.operations.URLTitleOperation.findTitle(URLTitleOperation.java:49)
        at javabot.operations.URLTitleOperation.handleChannelMessage(URLTitleOperation.java:32)
        at javabot.Javabot.getChannelResponses(Javabot.java:368)
        at javabot.Javabot.processMessage(Javabot.java:304)
        at javabot.BotListener.lambda$onMessage$14(BotListener.java:77)
        at javabot.BotListener$$Lambda$29/1950561585.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Expected authority at index 7: http://
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.failExpecting(URI.java:2854)
        at java.net.URI$Parser.parseHierarchical(URI.java:3102)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 10 more
```

**Comment by jottinger** [comment]
What's the input for this exception?

**Comment by evanchooly** [comment]
You see what I saw.  I'll see if there's more next time.  Otherwise we'll have to add some logging...
